### ISSUE TITLE
A request.

### ISSUE THREAD

**Issue by netsalesbg-ltd** [cattr-app/desktop-application#7]
Hello AmazingCat Devs,

We, me and my boss, like your platform, but it is missing some features, so I decided to add what I came up with.

I would like to be contributor for your Cattr platfrom. I have already started developing a useful feature on the three apps - desktop, backend and almost frontend (I just finished the backend and desktop apps, now starting the UI in the frontend).
The feature records the time spent in each open application and window title change.

If you are interested, please accept my access request in git.amazingcat.net, and I can push a feature branch for you to test it out.

Also I would like to ask why this desktop app does not have a repository in git.amazingcat.net?

Cheers,
Michael,
Netsales.BG Ltd.

**Comment by aVyarvelsky** [comment]
Hello, @netsalesbg-ltd . We're really happy you've liked our work. If you agree with point 11 of our[ SSPL license](https://www.mongodb.com/licensing/server-side-public-license) - then you're welcome. We will approve your access request. It is sounds great, that you've decided to add a feature like that into Cattr.
Moreover - we have a repository for desktop application at git.amazingcat.net, but another team is working on it and they publishing only stable and production-ready changes to Github. That's why you don't see it. But if you agree with our license I can ask the desktop team leader to add you as a developer, if you want so.

**Comment by netsalesbg-ltd** [comment]
Hey @aVyarvelsky,

Sorry for the late reply, but I have talked with my boss and he agrees to the license.
I'll be happy to contribute.

Michael

**Comment by aVyarvelsky** [comment]
Access granted. 
Please, push to our git.amazingcat.net and open a Merge Request, name starting with "DRAFT:" or "WIP:" prefix. That will tell us, that branch is active and we shouldn't touch it.

After you end - just remove prefix and assign merge to me.)
